### ISSUE TITLE
User can look up fruit information

### ISSUE THREAD

**Issue by kvnliang4** [kvnliang4/AJAX-Project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can look up fruit information.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can enter fruit name in input bar to search for desired fruit information
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103390498/173681546-fe01aa45-7458-4e6f-a61b-74333d4ed7bd.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add event listener to listen for user search input, **if input doesn't match any fruits, placeholder attribute switches to 'try again'?** 
- [x] create array of pictures and assign each a data attribute and assign the value to the fruit's name
- [x] loop through data for matching fruit and populate "Fruit Information Page" 
- [x] set the Name in the navbar as an anchor brings the view to the "Home Page"
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
