### ISSUE TITLE
User can create a new recipe

### ISSUE THREAD

**Issue by kvnliang4** [kvnliang4/AJAX-Project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can add/remove fruits to smoothie list
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user can add fruits to a recipe list

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103390498/173698606-bb4428d1-6522-497f-93c5-d02f0c6da30a.png)
![image](https://user-images.githubusercontent.com/103390498/175843276-d986d4b5-27b2-4cf7-996f-132aaf0e21a0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add modal with message asking if user wants to add fruit after clicking add button
- [x] create dom tree for recipe list and append any added fruit
- [x] create function to append dom content on load
- [ ] create buttons to add or subtract quantities of each fruit
- [ ] show total calories at the bottom
- [ ] create a 'create' button to save the recipe.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
