### ISSUE TITLE
User can add and delete recipes

### ISSUE THREAD

**Issue by kvnliang4** [kvnliang4/AJAX-Project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add and delete recipes
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Added recipes with be stored onto "Favorites recipe page". User is able to delete recipes
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103390498/173699584-3ec696ea-e4c3-464b-a8f5-ef01f0735dcf.png)
![image](https://user-images.githubusercontent.com/103390498/173699820-e2990258-91a7-4300-8b03-7e3b222b9b80.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add modals for adding and deleting recipes from favorite page
- [ ] create dom tree for favorites page. and append each entry
- [ ] loop through entries to find entry to be add/deleted
- [ ] create dropdown menu in nav bar to navigate between page views
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
