### ISSUE TITLE
User can sort fruit's nutritional value by category

### ISSUE THREAD

**Issue by kvnliang4** [kvnliang4/AJAX-Project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sort fruit's nutritional value by category
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can choose to sort nutritional values by each category by clicking on the  button of the desired category
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103390498/173702679-d856ff58-7198-44b1-b4d5-6f97f5d24498.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] listen for clicks for each button category. 
- [ ] update the dom tree when a button is clicked by replacing the values in each corresponding element for the old category with the value clicked category.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
