### ISSUE TITLE
User can sort each category by ascending/descending order

### ISSUE THREAD

**Issue by kvnliang4** [kvnliang4/AJAX-Project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sort each category by ascending/descending order
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can sort each category by ascending/descending order by clicking the arrow buttons 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] create arrow buttons and listen for clicks
- [ ] sort each value using sort() method
- [ ] update dom tree with new sorted entries
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
